/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hideakin_lib_time_TimeMachine */

#ifndef _Included_com_hideakin_lib_time_TimeMachine
#define _Included_com_hideakin_lib_time_TimeMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hideakin_lib_time_TimeMachine
 * Method:    setDate
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_hideakin_lib_time_TimeMachine_setDate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_hideakin_lib_time_TimeMachine
 * Method:    setDelta
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hideakin_lib_time_TimeMachine_setDelta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hideakin_lib_time_TimeMachine
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hideakin_lib_time_TimeMachine_reset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
